version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"
    networks:
      - pca-net

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - pca-net

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - pca-net
  blackbox:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    networks:
      - pca-net
  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - pca-net

networks:
  pca-net:
    driver: bridge
